<?php
/**
 * Default survey transcribed from the supplied Practitioner Discovery Survey.
 *
 * @package Soulmarke_Forms
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'title'           => 'Holistic Collective Practitioner Discovery Survey',
	'description'     => 'We are exploring the creation of Holistic Collective, a network designed to connect holistic and alternative health practitioners across the greater Louisville area. Before we determine exactly what the collective will offer, we want to understand what would be genuinely valuable to practitioners like you. This survey should take approximately 3–5 minutes.',
	'success_message' => 'Thank you for sharing your perspective. Your response will help shape Holistic Collective.',
	'recipients'      => array( 'andrea@soulmarke.com', 'Coral@soulmarke.com' ),
	'questions'       => array(
		array(
			'id'              => 'q_01',
			'title'           => 'Which best describes what you would most want from a practitioner collective?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => 'Something else',
			'options'         => array(
				'Community: opportunities to connect with other like-minded practitioners',
				'Collaboration: trusted practitioners I can work with and refer to',
				'Growth: opportunities to increase awareness and visibility for my practice',
				'Education: opportunities to learn from other practitioners',
				'A combination of these',
				'Something else',
			),
		),
		array(
			'id'              => 'q_02',
			'title'           => "How valuable would it be to have a trusted network of practitioners you could contact when a patient's needs extend beyond your scope of practice?",
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Extremely valuable',
				'Very valuable',
				'Somewhat valuable',
				'Not particularly valuable',
				'I already have a strong network like this',
			),
		),
		array(
			'id'              => 'q_03',
			'title'           => 'Which aspects of practitioner collaboration would be most valuable to you? Select all that apply.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Sending referrals to trusted practitioners',
				'Receiving referrals from other practitioners',
				'Collaborating on individual patient/client needs',
				'Having someone to consult with when a case is outside my expertise',
				'Building ongoing referral relationships',
				'Learning how other practitioners approach complex cases',
				'None of these are a priority for me',
			),
		),
		array(
			'id'              => 'q_04',
			'title'           => 'Which practitioner/community opportunities would you be most likely to participate in? Select all that apply.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Quarterly social or networking gatherings',
				'Informal practitioner meetups',
				'Private online community or Facebook group',
				'Peer-to-peer support and discussion',
				'Opportunities to exchange services or resources',
				'Educational gatherings or guest speakers',
				'Book discussions or practitioner reading groups',
				'I probably would not participate in these activities',
			),
		),
		array(
			'id'              => 'q_05',
			'title'           => 'How valuable would increased exposure to people in the greater Louisville community who may not yet know about your practice be?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Extremely valuable',
				'Very valuable',
				'Somewhat valuable',
				'Not particularly valuable',
				'I am currently at capacity and am not seeking additional exposure',
			),
		),
		array(
			'id'              => 'q_06',
			'title'           => 'Which forms of visibility or exposure would be most valuable to your practice? Select all that apply.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Being listed in a vetted practitioner registry/directory',
				'A profile page describing my practice and services',
				'A backlink from the collective website to my website',
				"Having my educational or promotional content shared through the collective's social media",
				"Having my content featured or amplified to the collective's audience",
				'Being featured in interviews, articles, podcasts, or practitioner spotlights',
				'Opportunities to participate in community education or events',
				'Referrals from other practitioners',
				'None of these are a priority for me',
			),
		),
		array(
			'id'              => 'q_07',
			'title'           => 'How valuable would it be for your practice to be included in a vetted local registry of holistic and alternative health practitioners?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Extremely valuable',
				'Very valuable',
				'Somewhat valuable',
				'Not particularly valuable',
				'I would only value this if it generated referrals or meaningful visibility',
			),
		),
		array(
			'id'              => 'q_08',
			'title'           => 'Which elements of a practitioner profile would be valuable to you? Select all that apply.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Practice name, location, and contact information',
				'Website backlink',
				'Description of my services/modalities',
				'Professional photo and/or logo',
				'Links to social media',
				'Ability to share educational content',
				'Ability to highlight specialties or areas of focus',
				'Patient/client testimonials or reviews',
				'I would not need a profile',
			),
		),
		array(
			'id'              => 'q_09',
			'title'           => 'If the collective had an active public-facing social media presence, how valuable would it be for your practice to have your content shared through those channels?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Extremely valuable',
				'Very valuable',
				'Somewhat valuable',
				'Not particularly valuable',
				'I would prefer to manage my own social media presence',
			),
		),
		array(
			'id'              => 'q_10',
			'title'           => 'Which would you be most interested in having the collective provide? Select up to 3.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 3,
			'other_option'    => 'Other',
			'options'         => array(
				'Practitioner registry/directory',
				'Website backlink and online visibility',
				'Social media exposure',
				'Referral network',
				'Practitioner networking events',
				'Peer support/community',
				'Practitioner collaboration/case consultation',
				'Educational events',
				'Community education and public awareness',
				'Content amplification/marketing opportunities',
				'Other',
			),
		),
		array(
			'id'              => 'q_11',
			'title'           => 'Which type of membership or participation would be most appealing to you?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Free participation in the public/community Facebook group',
				'Paid membership that includes a listing in the practitioner registry',
				'Paid membership that includes enhanced profile visibility and website backlink',
				'Paid membership that includes content promotion through collective channels',
				'Paid membership that includes access to practitioner-only networking/collaboration opportunities',
				'A higher-level membership that combines several of these benefits',
				'I would prefer to contribute through participation or promotion rather than paying a membership fee',
				'I would need to know the specific benefits before deciding',
			),
		),
		array(
			'id'              => 'q_12',
			'title'           => 'If you were a member, which contributions would you be willing to make? Select all that apply.',
			'description'     => '',
			'type'            => 'checkbox',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'Annual or monthly membership fee',
				'Sharing/promoting the collective with my own audience',
				'Mentioning the collective in a newsletter or mass email',
				'Creating or sharing social media content about the collective',
				'Providing educational content, quotes, or tips for collective content',
				'Participating in practitioner gatherings',
				'Referring patients/clients to other members',
				'Speaking at or participating in community events',
				'I would prefer not to make an ongoing contribution',
			),
		),
		array(
			'id'              => 'q_13',
			'title'           => 'If membership included having your practice listed in the registry, which statement best describes your interest?',
			'description'     => '',
			'type'            => 'radio',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(
				'I would consider paying specifically for the listing',
				'I would consider paying if the listing included a backlink and enhanced profile',
				'I would consider paying if the collective actively promoted my practice/content',
				'I would consider paying if membership also provided meaningful referrals/networking',
				'I would prefer a free listing with participation requirements',
				'I would not pay to be listed in a registry',
			),
		),
		array(
			'id'              => 'q_14',
			'title'           => 'Is there anything you would want from a practitioner collective that we have not asked about?',
			'description'     => 'Optional response.',
			'type'            => 'textarea',
			'required'        => false,
			'max_selections'  => 0,
			'other_option'    => '',
			'options'         => array(),
		),
	),
);
